
LOCAL_PATH := device/zte/nx402

USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/zte/nx402/BoardConfigVendor.mk

TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := nx402
#TARGET_BOARD_PLATFORM := apq8064
TARGET_BOARD_PLATFORM := msm8960
TARGET_BOARD_PLATFORM_GPU := qcom-adreno320

# Flags
TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp
COMMON_GLOBAL_CFLAGS += -DREFRESH_RATE=60 -DQCOM_HARDWARE

TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_ARCH_VARIANT_CPU := cortex-a9
TARGET_CPU_VARIANT := krait
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

BOARD_KERNEL_CMDLINE := console=null androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x3F ehci-hcd.park=3 maxcpus=4
BOARD_KERNEL_BASE := 0x80200000
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x02000000
BOARD_KERNEL_PAGESIZE := 2048

BOARD_USES_QCOM_HARDWARE := true
BOARD_USES_QCOM_LIBS := true


# PArtition sizes
BOARD_BOOTIMAGE_PARTITION_SIZE := 15728640 # /dev/mmcblk0p7, 15360 blocks
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 15728640 # /dev/mmcblk0p14, 15360 blocks
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2147483648 # /dev/mmcblk0p15, 2097152 blocks
BOARD_USERDATAIMAGE_PARTITION_SIZE := 2859941888 # /dev/mmcblk0p16, 2792912 blocks
BOARD_FLASH_BLOCK_SIZE := 1024

TARGET_PREBUILT_KERNEL := $(LOCAL_PATH)/kernel
TARGET_RECOVERY_INITRC := $(LOCAL_PATH)/ramdisk/recovery.rc
TARGET_RECOVERY_FSTAB := $(LOCAL_PATH)/ramdisk/fstab.nx402

BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_HAS_LARGE_FILESYSTEM := true

# Properties
#TARGET_SYSTEM_PROP += $(LOCAL_PATH)/system.prop

# GPS
TARGET_GPS_HAL_PATH := $(LOCAL_PATH)/gps
TARGET_NO_RPC := true

# Power
TARGET_POWERHAL_VARIANT := qcom

# SELinux
include device/qcom/sepolicy/sepolicy.mk

# TWRP
#HAVE_SELINUX := true
#DEVICE_RESOLUTION := 720x1280_cn
#RECOVERY_GRAPHICS_USE_LINELENGTH := true
RECOVERY_SDCARD_ON_DATA := true
BOARD_HAS_NO_REAL_SDCARD := false
#TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/msm_hsusb/gadget/lun0/file
TW_INTERNAL_STORAGE_PATH := "/emmc"
TW_INTERNAL_STORAGE_MOUNT_POINT := "emmc"
TW_EXTERNAL_STORAGE_PATH := "/data/media"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "data"
TW_NO_USB_STORAGE := false
#TWRP_EVENT_LOGGING := true
HAVE_SELINUX := true
#TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
#TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
#TARGET_RECOVERY_PIXEL_FORMAT := "RGB_565"
#TARGET_PREBUILT_RECOVERY_KERNEL := $(LOCAL_PATH)/kernel
